# Generated by Django 5.1.1 on 2024-09-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="creado el"
            ),
        ),
    ]
